version: 0.2

phases:
  build:
    commands:
      - echo Entering build phase...
      - echo Build started on `date`
      - aws s3 cp --recursive public/ s3://aws-website-martarealtime/
      - mvn package shade:shade
      - mv target/martaservice-1.0.jar .
      - unzip martaservice-1.0.jar
      - rm -rf target src buildspec.yml pom.xml martaservice-1.0.jar
      - aws cloudformation package --template template.yml --s3-bucket $S3_BUCKET --output-template template-export.yml
artifacts:
  files:
    - template-export.yml
